name: docker

on:
  push:
    tags:
      - docker-builds-dev/*

env:
  IMAGE_FQDN: ghcr.io/maldua/zimbra-foss-builder

jobs:
  publish-zimbra-foss-builder-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the zimbra-foss-builder Docker image
        run: |
          docker build --tag ghcr.io/maldua/zimbra-foss-builder:latest . -f Dockerfile-github-ubuntu-20.04
          docker push ghcr.io/maldua/zimbra-foss-builder:latest
